#! /bin/bash

#
# Start by staging src
#
cd "$(dirname "$0")"
source ../component_build_preamble staging/*

#
# Fix up versions as suggested by stack owner
#
sed -i -e 's/KIBANA_VERSION_PLACEHOLDER/'$(echo $KIBANA_VERSION)'/g' staging/Dockerfile

#
# Build kibana docker container. We do this in order to export /data
# and then use that to pull in a kibana.yml hosted in the host
# volume. The docker library version of kibana at the time of writing
# allows specifying the elasticsearch url as an environment variable
# passed it at runtime.
#
cd staging
exec_and_log "docker build --force-rm -t kibana:$KIBANA_VERSION ."
