#! /bin/bash

cd "$(dirname "$0")"
source ../util

if [ ! -d "$KIBANA_VOLUME" ]; then
    exit_error "Running kibana container without a host volume ($KIBANA_VOLUME)"
fi

log "Running kibana:${KIBANA_VERSION} listening on port ${KIBANA_PORT}, host volume $KIBANA_VOLUME" 
exec_and_log "docker run -d --name ${STACKNAME}_kibana -v $KIBANA_VOLUME:/data  -p $KIBANA_PORT:5601 -t kibana:$KIBANA_VERSION"
