#! /bin/bash
#
# Load support routines and configured environment for the stack.
#
cd "$(dirname "$0")"
source ../common/stack_preamble

#
# Run stack components
#
log "Run stack containers"
../common/elasticsearch/run >> $LOGFILE || exit_error "Failed to run elasticsearch container (need to run 'stack_stop'?)"
../common/kibana/run >> $LOGFILE || exit_error "Failed to run kibana container (need to run 'stack_stop'?)"
../common/logstash/run >> $LOGFILE || exit_error "Failed to run logstash container (need to run 'stack_stop'?)"

#
# Show running containers
#
exec_and_log "docker ps -a"

! read -r -d '' NEXTSTEP <<EOM

Telemetry streams can be pointed at collector, and data viewed in kibana:

Collector       @ ${COLLECTOR}
Streams         @ UDP/${TELEMETRYPORTUDP} supporting gprotobuf or JSON
Streams         @ TCP/${TELEMETRYPORTTCP} supporting compressed JSON
Kibana          @ http://${COLLECTOR}:${KIBANA_PORT}

Note: if host has multiple addresses, use an address which is reachable from source (router or browser as the case may be).

EOM

stack_script_postpend "$NEXTSTEP"
