#! /bin/bash

cd "$(dirname "$0")"
source ../common/stack_preamble

#
# Run stack components
#
log "Run stack containers"

../common/prometheus_pushgw/run >> $LOGFILE || exit_error "Failed to run prometheus push gateway containers (need to run 'stack_stop'?)"
../common/prometheus/run >> $LOGFILE || exit_error "Failed to run prometheus container (need to run 'stack_stop'?)"
../common/promdash/run >> $LOGFILE || exit_error "Failed to run prometheus dashboard container (need to run 'stack_stop'?)"
../common/logstash/run >> $LOGFILE || exit_error "Failed to run logstash container (need to run 'stack_stop'?)"

#
# Show running containers
#
log "Running containers:"
docker ps -a

! read -r -d '' NEXTSTEP <<EOM

Telemetry streams can be pointed at collector, and data viewed in promdash:

Collector       @ ${COLLECTOR}
Streams         @ TCP/${TELEMETRYPORTTCP} supporting compressed JSON
Prometheus      @ http://${COLLECTOR}:${PROMETHEUS_PORT}
Push GW         @ http://${COLLECTOR}:${PROMETHEUSPUSHGW_PORT}
Promdash        @ http://${COLLECTOR}:${PROMETHEUSDASH_PORT}

Note: if host has multiple addresses, use an address which is reachable from source (router or browser as the case may be).

EOM

stack_script_postpend "$NEXTSTEP"


