#! /bin/bash

cd "$(dirname "$0")"
source ../common/stack_preamble

docker rm -f ${STACKNAME}_logstash 2>/dev/null || echo "No logstash instance to kill"
docker rm -f ${STACKNAME}_promdash 2>/dev/null || echo "No promdash instance to kill"
docker rm -f ${STACKNAME}_promdash_db 2>/dev/null || echo "No promdash DB instance to kill (as expected)"
docker rm -f ${STACKNAME}_prometheus 2>/dev/null || echo "No prometheus instance to kill"
docker rm -f ${STACKNAME}_pushgw 2>/dev/null || echo "No prometheus push gateway instance to kill"

stack_script_postpend ""
