#! /bin/bash

#
# Load support routines and configured environment for the stack and stage it.
#
cd "$(dirname "$0")"
source ../common/stack_build_preamble

#
# Build docker images for components of stack
#
log "Building containers for stack components (takes a while, especially the first time)"
../common/prometheus/build >> $LOGFILE || exit_error "Failed to build prometheus for prometheus stack"
../common/prometheus_pushgw/build >> $LOGFILE || exit_error "Failed to build prometheus push gateway for prometheus stack"
../common/promdash/build >> $LOGFILE || exit_error "Failed to build prometheus dashboard for prometheus stack"
../common/logstash/build "${PWD}"/src >> $LOGFILE || exit_error "Failed to build logstash for prometheus stack"

#
# Build configuration from scratch
#
# Initialise the volumes is necessary, in preparation for
# configuration.
#
log "Initialising volumes for stack"
../common/logstash/volumes_init || exit_error "Failed to setup logstash volumes"
../common/prometheus/volumes_init || exit_error "Failed to setup prometheus volumes"
../common/promdash/volumes_init || exit_error "Failed to setup prometheus dashboard volumes"

#
# Update configurations in staging
#
log "Updating configuration to match stack environment"
sed --in-place \
    -e 's/COLLECTOR_PLACEHOLDER/'"$COLLECTOR"'/g' \
    -e 's/PROMETHEUSPUSHGW_PORT_PLACEHOLDER/'"$PROMETHEUSPUSHGW_PORT"'/g' \
    -e 's/PROMETHEUS_PORT_PLACEHOLDER/'"$PROMETHEUS_PORT"'/g' \
    -e 's/TELEMETRYJOBNAME_PLACEHOLDER/'"$TELEMETRYJOBNAME"'/g' \
    -e 's/TELEMETRYPORTTCP_PLACEHOLDER/'"$TELEMETRYPORTTCP"'/g' \
    staging/*

#
# Copy logstash and prometheus configs to expected host volume
# location
#
log "Copying base configurations to the host volumes for stack"
cp --verbose staging/ls_*.conf $LOGSTASH_VOLUME/conf.d  >> $LOGFILE 
cp --verbose staging/prometheus.yml $PROMETHEUS_VOLUME/conf.d  >> $LOGFILE 

stack_script_postpend "Run ./stack_run when you are ready to fire up the stack"
