#! /bin/bash

cd "$(dirname "$0")"
source ../util

#
# The prebuilt promdash image in the registry is ok.
# Strangely it is NOT versioned with a tag!
#
log "Pulling prom/promdash:latest docker image"
exec_and_log "docker pull prom/promdash"
