#! /bin/bash

cd "$(dirname "$0")"
source "../util"

if [ ! -d "$LOGSTASH_VOLUME" ]; then
    exit_error "Running logstash container without a host volume ($LOGSTASH_VOLUME)"
fi

log "Running logstash with volume $LOGSTASH_VOLUME:/data version $LOGSTASH_VERSION"
exec_and_log "docker run -d --name ${STACKNAME}_logstash -v $LOGSTASH_VOLUME:/data --net=host -t logstash:$LOGSTASH_VERSION"
