#! /bin/bash

cd "$(dirname "$0")"
source ../util

#
# The prebuilt prometheus image in the registry is ok.  Strangely it
# is NOT versioned with a tag! It exports /prometheus which we use at
# runtime to pass in a configurable /prometheus/conf.d/prometheus.conf
#
log "Pulling prometheus:latest docker image"
exec_and_log "docker pull prom/prometheus"
