#! /bin/bash

cd "$(dirname "$0")"
source ../util

if [ ! -d "$PROMETHEUS_VOLUME" ]; then
    exit_error "Running prometheus container without a host volume ($PROMETHEUS_VOLUME)"
fi

log "Running prometheus on port $PROMETHEUS_PORT with volume $PROMETHEUS_VOLUME and retention set to $RETENTION"
exec_and_log "docker run -d --name ${STACKNAME}_prometheus -p $PROMETHEUS_PORT:9090 -v $PROMETHEUS_VOLUME:/prometheus --entrypoint=/bin/prometheus prom/prometheus  -config.file=/prometheus/conf.d/prometheus.yml -storage.local.path=/prometheus/data -storage.local.retention=$RETENTION"
