#! /bin/bash

cd "$(dirname "$0")"
source ../util

#
# The prebuilt prometheus pushgw image in the registry is ok.
# Strangely it is NOT versioned with a tag!
#
log "Pulling prom/pushgateway:latest docker image"
exec_and_log "docker pull prom/pushgateway"
